import logging
class BaseStreamer:
    #Streamer has the functionality of updating PDA
    """
    Base class from which `.generate()` streamers should inherit.
    Handles batch generation updating corresponding PDAs.
    """
    def __init__(self, tokenizer, pda):
        self.tokenizer = tokenizer
        # Supporta sia singolo PDA che lista
        self.pdas = pda if isinstance(pda, list) else [pda]
        self.is_first_call = True
        
    def put(self, value):
        """Function that is called by `.generate()` to push new tokens"""
        
        # Helper per check pda eos
        def all_pdas_eos():
            return all(p.eos() for p in self.pdas)

        # Se tutti i PDA hanno già finito ed è first call
        if all_pdas_eos() and self.is_first_call:
             logging.warning(
            "⚠️ PDA sono già in stato finale (stack vuoto) PRIMA dell'inizio di una nuova generazione. "
            "Questo indica che manca un `pda.reset()` o che la grammatica è stata consumata interamente "
            "nella generazione precedente e il pda non è stato resettao -> stack vuoto []"
             )
             # Non raise immediately per permettere robustezza, ma loggato
             # raise "ERROR ON PDA RESET"

        if all_pdas_eos():
             self.is_first_call = True
             return

        # Handle batch dimension in `value`
        # value può essere un tensor di shape (batch_size,) o (1,) o scalar
        if hasattr(value, "shape") and len(value.shape) > 0:
            tokens_batch = value.view(-1).tolist()
        else:
            # Fallback scalar
             t = value.item() if hasattr(value, "item") else value
             tokens_batch = [t]

        # Se è la prima chiamata, contiene il/i prompt iniziale/i
        if self.is_first_call:
            # Solitamente nella prima call, 'value' contiene l'intero prompt input_ids.
            # Transformers streamer behavior:
            # "The `put()` method receives `token_ids` that are generated by the model."
            # Ma "Note that the `put()` method is called *after* the tokens are generated."
            # Però spesso la prima call include il prompt se configurato in certi modi, o solo il primo token generato?
            # BaseStreamer implementation originale assumeva che la prima call fosse il prompt iniziale (forse skip_prompt=True nel TextStreamer?)
            # Assumendo comportamento originale: scartiamo la prima chiamata.
            
            # Solo log prima sequenza
            if len(tokens_batch) > 0:
                gen_tok = tokens_batch[0]
                logging.info(f"Valore ricevuto in put (Seq 0 - First Call): {gen_tok}")
                logging.info(f"detokenizzato: {self.tokenizer.decode([gen_tok])}")

            self.is_first_call = False
            return 

        # Da qui in poi arrivano i token generati uno per volta (per sequence)
        # Se batch_size = 1, tokens_batch ha 1 elemento.
        # Se batch_size = 3, tokens_batch ha 3 elementi (i token nuovi per ogni seq).
        
        if len(tokens_batch) != len(self.pdas):
             # Mismatch dimensione batch vs pda
             # Se abbiamo un solo PDA ma 3 token generati -> Errore architetturale o broadcasting
             if len(self.pdas) == 1:
                 # Try to reuse single PDA (only safe if sequences identical)
                 pass 
             else:
                 logging.error(f"Mismatch: Received {len(tokens_batch)} tokens but have {len(self.pdas)} PDAs.")
                 # Procediamo finché possiamo
        
        # Iteriamo su ogni sequenza del batch
        for i, token_id in enumerate(tokens_batch):
            if i >= len(self.pdas):
                break
            
            pda = self.pdas[i]
            
            # Log solo per prima sequenza
            do_log = (i == 0)
            
            if do_log:
                logging.info(f"Token generato (Seq {i}): {token_id} ({self.tokenizer.decode([token_id])})")

            # Se il PDA è già finito, ignora update (padding o EOS già emesso)
            if pda.eos():
                continue

            try:
                pda.next_state(token_id)
                if do_log:
                    logging.info(f"Stack PDA aggiornato (Seq {i}): {pda.stack[::-1]}")
            except Exception as e:
                logging.error(f"Errore durante aggiornamento PDA {i} con token {token_id}: {e}")
                logging.error(f"Stack corrente: {pda.stack}")
                raise


    def end(self):
        """
        Chiamato da .generate() per segnalare fine generazione.
        Resetta lo stato per permettere nuove generazioni.
        """
        logging.info("=== Fine generazione ===")
        
        # Verifica finale consistenza per tutti i PDA
        all_empty = True
        for i, pda in enumerate(self.pdas):
            if not pda.eos():
                logging.warning(f"⚠ Generazione terminata ma stack PDA {i} non vuoto: {pda.stack[::-1]}")
                all_empty = False
            else:
                # logging.info(f"✓ Stack PDA {i} correttamente vuoto")
                pass
        
        if all_empty:
             logging.info("✓ Tutti gli stack PDA correttamente vuoti")
        
        # Reset completo dello stato per tutti
        self.is_first_call = True
        for pda in self.pdas:
            pda.reset() 

        logging.info("Streamer e tutti i PDA resettati per prossima generazione")

        